topics:
- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 50

- name    : sonar_obstacle_avoidance
  topic   : sonar/cmd_vel
  timeout : 0.5
  priority: 80

- name    : pad
  topic   : pad_teleop/cmd_vel
  timeout : 0.5
  priority: 100