topics:
-
  name    : move_base
  topic   : move_base_cmd_vel
  timeout : 0.5
  priority: 10
-
  name    : sonar_obstacle_avoidance
  topic   : sonar_cmd_vel
  timeout : 0.5
  priority: 50
-
  name    : joysticks
  topic   : joy_vel
  timeout : 0.5
  priority: 100