topics:
-
  name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 10
-
  name    : sonar_obstacle_avoidance_left
  topic   : sonar_left/cmd_vel
  timeout : 0.5
  priority: 51
-
  name    : sonar_obstacle_avoidance_right
  topic   : sonar_right/cmd_vel
  timeout : 0.5
  priority: 50
-
  name    : joysticks
  topic   : joy_vel
  timeout : 0.5
  priority: 100